### ISSUE TITLE
Cannot find type 'Fields' in scope

### ISSUE THREAD

**Issue by SurgeTO** [maticzav/swift-graphql#16] opened 2021-01-18 18:30 UTC
**Describe the bug**
Hi,

First of all, thanks for creating this awesome package.

I just added SwiftGraphQL to my project and successfully generated the API.swift code, however the app does not compile anymore. I'm getting a ton of "Cannot find type 'Fields' in scope" errors from that API.swift file.

**To Reproduce**
Add SwiftGraphQL 1.1.2 to your project, setup the codegen part and, add the API.swift to your project and build the app.

Thanks.

**Comment by maticzav** [comment] 2021-01-19 11:16
Hi, 

Thank you for opening the issue! 

I experience the same problem many times in my own projects. The problem is that version in the code generator gets decoupled from the project. I am not sure how to make this easier, but I usually fix this by manually changing the SwiftGraphQL version in the generator. Then, I retrigger the generation, and it works again.

Let me know if that fixed the problem for you 😄 

> PS.: I encourage you to use 2.0.0-beta.x versions since they are more or less just fixes of 1.x.x version with one breaking change (you'll have to write `try` when decoding). I could've made a change, but since this is a young library I didn't want to reach v5 in three months if I had realized more breaking changes were necessary.

**Comment by justvil** [comment] 2021-01-25 19:33
Original poster here. Thanks @maticzav, moving to 2.0.0-beta.x resolved my issue.

**Closed** 2021-01-26 08:27 UTC
Labels: question
