### ISSUE TITLE
GraphQLWebSocket' does not conform to protocol 'WebSocketDelegate'

### ISSUE THREAD

**Issue by confusionhill** [maticzav/swift-graphql#156] opened 2023-09-07 09:46 UTC
**Describe the bug**
Hello, i am quite new to this exiting dependency. SO I tried to install Grapql, swift Graphql, and the GraphQL client using SPM and I got this error. How do I fix it (other than complying to the protocol request) ?

Thank you

ios : 15
<img width="813" alt="Screenshot 2023-09-07 at 16 45 28" src="https://github.com/maticzav/swift-graphql/assets/71744284/b7dde53d-3053-466c-bcb7-81fcca087f6f">

**Comment by pokryfka** [comment] 2023-09-24 07:30
Seems like a duplicate of #155 
Caused by a "patch" change in Starscream

**Closed** 2023-10-04 03:32 UTC
