### ISSUE TITLE
Concurrency related crash in SwiftGraphQLClient

### ISSUE THREAD

**Issue by nordfogel** [maticzav/swift-graphql#98] opened 2022-10-26 14:49 UTC
**Describe the bug**
Crash due to concurrency issue of SwiftGraphQLClient Client in Core.swift function 
`public func execute(operation: Operation) -> Source`
line 127: active[operation.id] = source
accessing (read/write) of active dictionary from concurrent threads

**To Reproduce**
Query from different threads simultaneously 

**Expected behavior**
Client can handle concurrent threads accordingly.

**Screenshots**
none

- iOS 16
- Swift build tool version: 5.7
- Xcode: 14.0.1

**Additional context**
none

**Comment by maticzav** [comment] 2022-11-01 20:19
Hey there 👋 ,

Thank you for reporting this. Is there any chance that you provide a reproduction repository? It would really to have something to start with and it seems like you already have something.

I am also interested in helping you specifically resolve this issue. Let me know what works for you 😄

**Comment by yonaskolb** [comment] 2023-07-16 11:27
Just a note that we've seen this too, but can't reproduce reliably yet

**Comment by maticzav** [comment] 2023-07-16 14:58
@yonaskolb do you know of any good resources that I could check out to fix this?

**Comment by shaps80** [comment] 2023-10-19 16:59
@nordfogel / @yonaskolb I'm currently exploring this as I recognise thread safety is an issue.

I'll be exploring this shortly, starting via a Discussion so keep an eye for that. Due to the limited context above, I'm going to close this issue but don't worry, we are exploring improving concurrency ASAP 👍

Thanks.

**Closed by shaps80** 2023-10-19 16:59 UTC
Labels: bug
